### ISSUE TITLE
What is the unification algorithm lacking in order to handle application of a meta?

### ISSUE THREAD

**Issue by atennapel** [AndrasKovacs/elaboration-zoo#10]
https://github.com/AndrasKovacs/elaboration-zoo/blob/91e39dc712b4e47ade228d0a51c86dd506263f78/03-holes/Main.hs#L477

Could you expand a little on this comment? What is the unificiation algorithm lacking in order to handle this situation with a dependent function type? I've seen the paper ["A tutorial implementation of dynamic pattern unification"](https://www.google.com/url?sa=t&source=web&rct=j&url=http://adam.gundry.co.uk/pub/pattern-unify/&ved=2ahUKEwjWrPqT8ZnmAhURLVAKHRgrA6oQFjABegQIBhAE&usg=AOvVaw19oOnn12hZrQ_ojW82UsEv) which is about "dynamic" pattern unification, I think that means that constraints can be postponed. Would that algorithm be able to handle it?

Also `freshPi` seems to create a dependent function type? So this comment is incorrect?

On a related note, can the term `\f x. f x` be solved (with unsolved metas)? What happens in my implementation is that `f` will get a fresh meta `?0`, this meta is then applied to `x`, which will try to refine `?0` to a pi type. But the new metas that are created for the pi type can depend on `f` and `x` and so `?0` can not be unified with this new pi type. I believe your implementation also has this problem?

**Comment by AndrasKovacs** [comment]
Comments appear to be outdated, I removed them. It's still a bit doubtful that we can do much by trying to unify with a fresh dependent pi, but I removed the comment anyway.

> I think that means that constraints can be postponed. Would that algorithm be able to handle it?

The key here is not postponing (although it is a nice improvement in general) but pruning. We try to unify with a fresh pi, but if we later learn that it should be actually a non-dependent function, then pruning lets us remove unnecessary dependence from the codomain meta. Without pruning, refining a fresh pi to a non-dependent function usually fails.

**Comment by atennapel** [comment]
Aah I see, makes sense.

I think the way you do it now is incorrect, because the `freshPi` creates metas in the current typing environment while it should do it in the same environment as the original meta. Or else you get scoping errors. Am I correct?

**Comment by AndrasKovacs** [comment]
The way it is implemented now is technically correct, but again the lack of pruning means that we trip up  on extra bound var dependencies. 

I think we could optimize this by applying the fresh domain meta to the spine of the original meta, and the fresh codomain meta to that spine extended with an extra var. I'm not 100% sure that this is correct, probably it is.

**Comment by atennapel** [comment]
> The way it is implemented now is technically correct, but again the lack of pruning means that we trip up on extra bound var dependencies.

I don't see how it could be correct, for example:
`\x f. f x`
Here first x will get a fresh meta `?0`, then later this meta will be refined to `(x: ?1 f) -> ?2 f x`, now `f` has escaped its scope. Please correct me if I'm wrong.

> I think we could optimize this by applying the fresh domain meta to the spine of the original meta, and the fresh codomain meta to that spine extended with an extra var. I'm not 100% sure that this is correct, probably it is.

I think this is the way to do it correctly, I have implemented this and it seems to work correctly.

**Comment by atennapel** [comment]
> The way it is implemented now is technically correct, but again the lack of pruning means that we trip up on extra bound var dependencies.

What about the term `\f x. f x`. First `f` will have type `?0` then after `x` is in scope it will be refined to `(y: ?2 x) -> ?3 x y`. `x` has escaped its scope at this point, since `f` should not have access to it, but it has in its type now.

> I think we could optimize this by applying the fresh domain meta to the spine of the original meta, and the fresh codomain meta to that spine extended with an extra var. I'm not 100% sure that this is correct, probably it is.

It seems to me this is the correct way to do it. I have implemented it this way and it seems to work well enough.

**Comment by AndrasKovacs** [comment]
> What about the term \f x. f x. First f will have type ?0 then after x is in scope it will be refined to (y: ?2 x) -> ?3 x y. x has escaped its scope at this point, since f should not have access to it, but it has in its type now.

Scope escape is not possible, because `(y: ?2 x) -> ?3 x y` would be all ill-scoped solution to ?0, as it depends on `x` but `?0` can't depend on it. Pruning would remove the `x` dependency from ?2 and ?3.

> It seems to me this is the correct way to do it. I have implemented it this way and it seems to work well enough.

I think that the current solution + pruning would be more general, but your version simpler and definitely works better without pruning. You can change it to your version in this repo if you'd like to.

**Comment by atennapel** [comment]
Aah right thanks. I misunderstood you. I noticed `\f x. f x` failed to typecheck and called it incorrect, but it's actually correct, it just won't typecheck.
