### ISSUE TITLE
Inferring annotated lambdas

### ISSUE THREAD

**Issue by atennapel** [AndrasKovacs/elaboration-zoo#14]
What would be a good way to infer annotated lambdas?
Currently I am doing the following, using DeBruijn indeces/levels (in TypeScript, I hope it's still readable):
```typescript
if (tm.tag === 'Abs') {
    // 1. check that the parameter type is valid
    check(ts, vs, k, tm.type, VType);
    // 2. evaluate the parameter type
    const type = evaluate(tm.type, vs);
    // 3. typecheck the body
    const rt = synth(extendV(ts, type), extendV(vs, VVar(k)), k + 1, tm.body);
    // 4. check that the parameter is not used in the body (if the parameter is erased)
    if (tm.meta.erased && erasedUsed(0, tm.body))
      return terr(`erased argument used in ${showTerm(tm)}`);
    // 5. return the Pi type, (parameter type) -> body type
    return evaluate(Pi(tm.meta, tm.type, quote(rt, k + 1, false)), vs);
}
```

This works great, but I am concerned about the quoting when constructing the pi type. How would you type check annotated lambdas? To avoid quoting I'd have to turn the return type `rt` in to a closure for the `Pi`, can that be done?

**Comment by atennapel** [comment]
I see in https://github.com/AndrasKovacs/icfp20sub/blob/master/fcif/Elaboration.hs that you also quote the body of the pi when elaborating an annotated lambda, so I assume you don't know a better way.

**Comment by AndrasKovacs** [comment]
`liftVal` is not efficient, you're right about that. In `fcif` I didn't optimize performance. The fastest way I know is to use local eval/quote with glued evaluation, and also do inference for n-ary lambdas, so that we don't have to `liftVal` on each lambda, and only do one lifting over multiple binders.

**Comment by atennapel** [comment]
I see. So there's no way to avoid the `quote`, but there are ways to minimize the impact. Thanks!
