### ISSUE TITLE
Adding primitives

### ISSUE THREAD

**Issue by atennapel** [AndrasKovacs/elaboration-zoo#23]
I wanted to add primitives in the domain, for example consider the primitive:
`unsafeCast : {a : *} -> {b : *} -> a -> b`
With reduction rule
`unsafeCast {a} {b} x ~> x (if x is not neutral)`

I thought it would be simple to add is a new kind of Head of neutrals, but I'm hitting on the problem of when to actually reduce them. For example if you have the closure:
`\v -> Neutral "unsafeCast" [a, b, v]`
Then applying this closure will not actually recompute and reduce the primitive.
One way I thought of is to "guard" closure application such that after a closure application it is checked if a primitive can now be reduced. This means having to go through the spine of the neutral as well, because you might have something like:
`\v -> Neutral "unsafeCast" [Neutral "unsafeCast" [a, b, v]]`

Does this approach seem reasonable to you, or do you have a better idea maybe?

My goal is implement the elements of "The Gentle Art of Levitation". I was hoping that adding `Desc` and the constructors and other constructs as primitives would allow me to keep my syntax simpler. Basically I want axioms that also can reduce if their spine takes a certain form.

**Comment by atennapel** [comment]
Should be an eliminator instead of a head.

**Comment by AndrasKovacs** [comment]
[Here](https://github.com/AndrasKovacs/setoidtt-proto/blob/master/proto/Evaluation.hs#L293) are a some examples for handling primops. In summary, we have for a primop:
- A new symbol (nullary constructor) in the core syntax.
- A new neutral head, for when the evaluation of a primop gets stuck.
- An evaluation rule in `eval`, which consists of as many `VLam`-s as needed to apply the primitive to enough arguments, so that the computation rule can be tested. We return a primop-headed neutral if the evaluation rule is stuck.

There are more ways to make this work, I usually use the above scheme because it allows me to partially apply a primop without restriction, and generally treat is as a postulated constant with extra computation rules.

**Comment by atennapel** [comment]
Thanks, that's clever. I will try to implement something similar.

**Comment by atennapel** [comment]
You could also implement `fst` and `snd` for dependent pairs like this, couldn't you? Although that does make the head more complicated than having `fst` and `snd` as eliminations in the spine. What do you think?

**Comment by AndrasKovacs** [comment]
Yes, and what's better is that we *don't* have to change spines at all. We simply have `Fst :: Tm`, and `eval Fst = VLam $ \v -> vFst v` or something like this, where `vFst` builds the usual projection spine.

**Comment by atennapel** [comment]
Aah that's true, but would a `fst`/`snd` headed neutral have downsides compared to a more complicated spine?

**Comment by AndrasKovacs** [comment]
Yes, projections in spines are clearly much better than as heads. In older versions of Coq, they actually had projections as symbols, and then they switched to primitive (spine) projections, which were clearly more convenient and efficient.

One point of neutrals is that we want as easy as possible access to the expression which blocks computation. If projection is a constant, it's not actually the head which blocks computation, but its argument, and if we have something like a neutral `fst t1 t2 t3`, then the blocking `t1` expression is buried under all outer applications. 

For eta-conversion checking it's also clear that we want projections in spines. It works the same way as eta conversion for functions. Type theoretically, functions and sigmas are often grouped together as "negative" types, and I think I've even seen function application being called a "projection".

**Comment by atennapel** [comment]
While on the topic of eta-conversion. I saw Agda has eta-conversion for the unit type (for records in general). If I add a primitive unit type then can I just conclude (if I follow your system in `elaboration-zoo`) that whenever I unify `() ~ x` or `x ~ ()` that it should be accepted? Since both sides are typechecked before unifying I can assume that `x : UnitType` and so `x` must be `()`.

**Comment by AndrasKovacs** [comment]
`() ~ x` and `x ~ ()` works, but this is weaker than unit eta in Agda, where we also have `x ~ y` for variables `x : ()` and `y : ()`. 

For non-empty record types, we get the full eta this way, only the unit type is where we don't get it. Agda has type-directed conversion checking, so it implements unit eta by matching on the type.

I personally don't think that type-directed conversion is worth it just for unit eta; it adds more complexity and has some performance cost.

**Comment by atennapel** [comment]
Ah I see, thanks! Luckily the weak unit-eta is enough for my purposes.

**Comment by atennapel** [comment]
I have another question, related to the weak eta law for unit. If we add an equality type:
```
Eq : (t : U) -> (x y : t) -> *
Refl : (t : U) -> (x : t) -> Eq t x x
```
And the weak eta:
```
Refl ~ x
```
Is this consistent? Will it allow us to define equality elimination (because the weak eta law for unit is enough to get induction for unit)?

**Comment by AndrasKovacs** [comment]
> Is this consistent?

Yes. It's called uniqueness of identity proofs (UIP). But it's inconsistent with univalence.

> Will it allow us to define equality elimination (because the weak eta law for unit is enough to get induction for unit)?

No. With only UIP and no elimination, it's consistent to assume `Eq A B ~ Unit`.

**Comment by atennapel** [comment]
If we have `Void = {A : *} -> A` and `Refl ~ x` and `Unit = Refl {*} {Void}`, would that be consistent with transport. My feeling is yes.

**Comment by AndrasKovacs** [comment]
Sure, you're not doing anything with `Eq`, just defining `Void` and `Unit`.

**Comment by atennapel** [comment]
Great, so in that scenario you get unit with (weak) eta for free.
