### ISSUE TITLE
Unification of decoding functions

### ISSUE THREAD

**Issue by atennapel** [AndrasKovacs/elaboration-zoo#26]
In ["Dependently Typed Programming in Agda"](http://www.cse.chalmers.se/~ulfn/papers/afp08/tutorial.pdf) (P33) a universe for overloading is shown. Let me give a minimal example (in Agda-like syntax):
```
TYPE : * = Bool
BOOL : TYPE = True
NAT : TYPE = False

decode : TYPE -> * = \t. if t then Bool else Nat

eq : (t : TYPE) -> decode t -> decode t -> Bool
= \t. indBool (\t. decode t -> decode t -> Bool) eqBool eqNat t

eq BOOL True False == False
eq NAT 1 1 = True
```
Now in Agda apparently the `TYPE` can be inferred. But in the system of this repo obviously it will not:
```
eq _ 1 1
Results in the unification:
Nat ~ decode ?1
Which then tries to solve (with if-then being the eliminator in the spine):
?1 (if-then Bool else Nat) := Nat
```
This fails because there is an eliminator in the spine of `?1`. Now I can see a way to solve this in this special case because `if-then` has exactly two possible results, so we could try to unify the results and see:
```
try Bool
Bool := Nat
fail
try Nat
Nat := Nat
success
solve ?1 := False
```

Does this seem like a reasonable thing to add to you, in order to beef up the unification in some cases? Or do you know of a more general approach to try and solve problems like this?

**Comment by AndrasKovacs** [comment]
This is already supported in current Agda. See e.g. section 5 of [this](https://gallais.github.io/pdf/tyde19.pdf). It does not lose any unification solutions if implemented conservatively, so it's a reasonable thing to add.

**Comment by atennapel** [comment]
Thanks for the reference!

**Comment by ollef** [comment]
FWIW, Sixty has this kind of conservative [case inversion ~hacked in~ implemented](https://github.com/ollef/sixty/blob/eba91e21a483df8dfaca0dff4e0dfe9d9c8a773b/src/Elaboration/Unification.hs#L399).

It's sometimes [surprisingly powerful](https://github.com/ollef/sixty/blob/7294718c1287ab0d5d28bd298ad4b70e76d6366b/tests/singles/type-checking/case-inversion.vix#L17).

**Comment by atennapel** [comment]
Yeah that's awesome! So in your case I see in:
```
case scrutinee of
  con1 vs1 -> con1' es1
  con2 vs2 -> con2' es2
==
con1' es1'
```
The `con1'` is matched by a simple equality check of the constructor? So no unification/backtracking there.

**Comment by ollef** [comment]
Yeah, that's right. It's a quite superficial test to avoid backtracking.

**Comment by atennapel** [comment]
This is where having native datatypes and a pattern matching construct also seems to make things easier. In "Gentle art of levitation" and my system (unit, bool, fix) even a simple sum type `A + B` is `(b : Bool) ** if b then A else B`, which makes the same equation look more like `?0 fst (if-then (\a. v1) (\b. v2)) (snd ?0) == v`.
