### ISSUE TITLE
What is the need for InsertedMeta?

### ISSUE THREAD

**Issue by atennapel** [AndrasKovacs/elaboration-zoo#28]
I saw you updated the code for implicit arguments, it's very clean now. The only thing that I don't understand is the need for `InsertedMeta`. This was not in the code before, just `Meta` is enough, you can create spine (filter out non-bound variables) in `freshMeta`. With `InsertedMeta` the creation of the spine is delayed a little bit because it's done in evaluation. Is the reason for `InsertedMeta` efficiency/performance, because it seems redundant in the presence of `Meta`.

**Comment by Boarders** [comment]
Relatedly, I wondered if you could just have let-defined indices and a defined context so the bound variable spine only needs the depth to do the correct binding.

**Comment by AndrasKovacs** [comment]
Efficiency, and when we get to more advanced/typed unification, simplicity as well. Without `InsertedMeta`, fresh meta creation is linear in local scope and evaluating an inserted meta is quadratic. With `InsertedMeta`, it's constant time and linear respectively, and also simpler. 

> Relatedly, I wondered if you could just have let-defined indices and a defined context so the bound variable spine only needs the depth to do the correct binding.

I don't really understand, can you explain?

**Comment by AndrasKovacs** [comment]
That doesn't work, because bound variables can become defined during evaluation. For example, take

    let f = \x. t in
    f u

In the scope of `t`, `x` is bound, but during evaluation it becomes defined by `u`. It's not possible to separate defined and bound contexts.

**Comment by Boarders** [comment]
Ah I see, that makes perfect sense.

**Comment by atennapel** [comment]
Could `Meta` be removed then?

**Comment by AndrasKovacs** [comment]
> Could Meta be removed then?

No, only `Meta` can be returned from quoting.

**Comment by hirrolot** [comment]
> No, only `Meta` can be returned from quoting.

Why not return `InsertedMeta` with an empty list from quoting?

**Comment by AndrasKovacs** [comment]
@hirrolot what's the advantage of that? 
During quotation, metas are just arbitrary functions applied to arbitrary args, without any relation to the shape of the current scope, so it doesn't make sense to use `InsertedMeta`. We might want to compress or optimize meta spine representations but those would be different from `InsertedMeta`.

**Comment by hirrolot** [comment]
> what's the advantage of that?

We could then remove `Meta` completely and only use `InsertedMeta`. Everywhere in the code (`04-implicit-args`), we process `InsertedMeta` with an empty list in the same way as `Meta`.

**Comment by AndrasKovacs** [comment]
`eval` in its current state would crash on `InsertedMeta` with empty list.
