### ISSUE TITLE
Why do we generate a fresh identifier in `quote`?

### ISSUE THREAD

**Issue by Hirrolot** [AndrasKovacs/elaboration-zoo#31]
I'm trying to grasp how Normalization by Evaluation works. Unfortunately, the resources are outright scanty at the moment. I've stumbled upon this example code:

https://github.com/AndrasKovacs/elaboration-zoo/blob/0e710812c38e2be8a2fce72a9350815be28e01a2/01-eval-HOAS-names/Main.hs#L96

I wonder why we need to generate a fresh `x` if we don't perform substitution, since this step has already been done during evaluation. Am I missing something?

**Comment by AndrasKovacs** [comment]
Consider the term `let f = \x y. x y in \y. f y`. If we normalize this, and we don't do the variable freshening in quoting, we get `\y y. y y` as output, which is not correct (not convertible to the input term). The `VLam` result of `f y` depends on `y` as a free variable, so we can't pick `y` for the binder name for quoting this `VLam`. Instead, we pick a name which doesn't shadow anything from the current scope, which prevents any free variable in closure bodies to become conflated with the new binder.

**Comment by Hirrolot** [comment]
Oh, that's right, I was just looking for this kind of logic in `eval` itself. Thanks!
