### ISSUE TITLE
Is the implementation of `invert` correct?

### ISSUE THREAD

**Issue by kuchenkruste** [AndrasKovacs/elaboration-zoo#32]
Hey there 👋!

First of all, I would like to thank you for this great repository! I try to understand how elaborators for dependently typed languages work and how they can be implemented efficiently. It is very helpful how you demonstrate the different features and implementation approaches in an incremental way here.

While following your explanations and your code, I came across the `invert` function of package `05-pruning` and especially the inner function `go`:

```haskell
let go :: Spine -> IO (Lvl, IS.IntSet, IM.IntMap Lvl, Pruning, Bool)
      go []             = pure (0, mempty, mempty, [], True)
      go (sp :> (t, i)) = do
        (dom, domvars, ren, pr, isLinear) <- go sp
        case force t of
          VVar (Lvl x) -> case IS.member x domvars of
            True  -> pure (dom + 1, domvars,             IM.delete x ren,     Nothing : pr, False   )
            False -> pure (dom + 1, IS.insert x domvars, IM.insert x dom ren, Just i  : pr, isLinear)
          _ -> throwIO UnifyError
```

My question concerns the relevant lines after we match on `force t`. If I understand this correctly, we first check if we already encountered the variable `x` in the spine (`case IS.member x domvars`). If this is indeed the case, we face a non-linear pattern, which is why we try to prune *all* occurrences of `x`. For this, we add `Nothing` to the pruning-mask `pr` and remove `x` from the renaming (`IM.delete x ren`). 

However, what about previous occurrences of `x` in the pruning-mask `pr`? If `x` is indeed an element of `domvars`, there must have been a previous call to `go` which, in turn, added `Just i` to `pr` at the level of the first occurrence of `x`. Hence, when we use the partial renaming for a unification problem `?0 a a b =? rhs` the variable `a` will neither be renamed in `rhs` nor is it fully pruned, as the mask should equal `[ Just Expl, Nothing, Just Expl ]`. So my question at this point is: Is this observation right or do I misunderstand something important about pruning? 

I would really appreciate your help in this matter. I can imagine that this may be relevant to others as well, which is why I opened an issue for this. 

Thank you very much for your time! 🙏

**Comment by AndrasKovacs** [comment]
Hi,

It's very much a bug, thanks! Something like the following would be nicer and correct:

- A first pass over the spine returns a partial renaming, a set of nonlinear vars and a list of vars (which is just the original spine, forced).
- The second pass converts the list of vars to a pruning.

PR is welcome. I'm very busy right now but sometime next week I'll patch this.

**Comment by kuchenkruste** [comment]
Here we go 🥳. I hope, I did not introduce any other bug 🤞.

**Comment by AndrasKovacs** [comment]
Thanks!
