### ISSUE TITLE
Can you translate let-expressions to lambda abstractions?

### ISSUE THREAD

**Issue by atennapel** [AndrasKovacs/elaboration-zoo#4]
If I use something like your algorithm (with annotated lambdas added) then if I translate let-expressions as follows:
```
let x : t = v in b ~> (\(x:t). b) v
```
Then trying the following:
```
let IdType : * = (t:*) -> t -> t in
let id : IdType = \t x . x in
id
```
Will translate to:
```
(\(IdType:*). (\(id:IdType). id) (\t x. x)) ((t:*) -> t -> t)
```
Which does not typecheck, because when you typecheck the first lambda the value `((t:*) -> t -> t)` is not added to the value environment.

I think I could fix by special casing applications of the form `(\(x:t). b) v`, adding `v` to the value environment instead of the variable `x`. This feels a bit dirty though.

What do you think? Can let-expressions be translated to lambdas? Is the special case reasonable? Or is adding let-expressions to the core language reasonable?

**Comment by AndrasKovacs** [comment]
[Andrej's answer](https://cs.stackexchange.com/questions/114640/why-does-coq-include-let-expressions-in-its-core-language) is correct. In short, if we want to use lambda, then we lose well-typed subexpressions. If we want to repair this, then we end up with something which is essentialy just `let`.

**Comment by atennapel** [comment]
Thanks, in that I will add let-expressions to my core as well :)
