### ISSUE TITLE
Some hints regarding deBruijn implementation of meta solving

### ISSUE THREAD

**Issue by atennapel** [AndrasKovacs/elaboration-zoo#5]
Could you provide some hints regarding meta solving with a deBruijn implementation? Specifically, what would `checkSp` and `newMeta` look like?

**Comment by atennapel** [comment]
I'm using https://github.com/brendanzab/rust-nbe-for-mltt now, which seems to use your algorithm but with deBruijn indeces/levels.

**Comment by ice1000** [comment]
I suppose the reason why we parameterize the solved meta with local variables is about scoping. With DBI, there won't be ambiguous names, therefore I didn't do the parameterization -- just solve the meta during conversion check and put them into the meta context. When a definition is checked, I inline all the solved metas.

**Comment by ice1000** [comment]
For the record, here's [my impl](https://github.com/owo-lang/narc-rs/blob/84bdf30b9382b416c7127243ac69f7b4d8ecde5e/src/check/rules/term/unify.rs#L146-L180). It's using de Bruijn indices and meta indices.
