### ISSUE TITLE
Unification should check for spine length equality?

### ISSUE THREAD

**Issue by atennapel** [AndrasKovacs/elaboration-zoo#6]
Shouldn't the spines be the same length here:
https://github.com/AndrasKovacs/elaboration-zoo/blob/d89688abd814d977968a2c7ca0ff4aecd40c3f2c/03-holes/Main.hs#L396

**Comment by AndrasKovacs** [comment]
The two sides in unification always have the same type, so if the heads are equal, then the spines cannot be of different length (because then the sides would have different type).

**Comment by atennapel** [comment]
Right, that makes sense.
