### ISSUE TITLE
checkSolution, should meta solution be checked?

### ISSUE THREAD

**Issue by atennapel** [AndrasKovacs/elaboration-zoo#9]
In `checkSolution` (https://github.com/AndrasKovacs/elaboration-zoo/blob/91e39dc712b4e47ade228d0a51c86dd506263f78/03-holes/Main.hs#L335) the type to be checked is quoted but the meta solutions are not inlined (no zonking). That makes the assumption that all meta solution in the type are valid for the meta we are trying to solve. Is this assumption valid?

**Comment by AndrasKovacs** [comment]
Metas are unfolded in quoting. The `force` does it in [this line](https://github.com/AndrasKovacs/elaboration-zoo/blob/91e39dc712b4e47ade228d0a51c86dd506263f78/03-holes/Main.hs#L290).

**Comment by atennapel** [comment]
Aah of course, thanks.
